/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    CountdownRing: typeof import('./src/components/CountdownRing.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    Leaderboard: typeof import('./src/components/Leaderboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
